# generates a new pa_schemer.ml

ocamlrun ../boot/camlp5 ./pa_schemer.cmo -I ../boot pa_extend.cmo ./pr_r.cmo ./pr_extend.cmo ./pr_rp.cmo ./q_phony.cmo pa_r5rs.ml > tmp

mv pa_r5rsr.ml pa_r5rsr.ml.old
sed -e 's/^;; \(.*\)$/(* \1 *)/' -e 's/^; \(.*\)$/(* \1 *)/' -e 's|./pa_r5rsr.cmo|pa_r.cmo pa_rp.cmo|' -e 's/$Id.*\$/File generated by pretty print; do not edit!/' tmp > pa_r5rsr.ml
rm -f tmp

exit

# builds pa_r5rsr.cmo

echo ocamlrun ../boot/camlp5 -nolib -I ../boot pa_r.cmo pa_rp.cmo pa_extend.cmo q_MLast.cmo pr_dump.cmo -mode S -o pa_r5rsr.ppo pa_r5rsr.ml
ocamlrun ../boot/camlp5 -nolib -I ../boot pa_r.cmo pa_rp.cmo pa_extend.cmo q_MLast.cmo pr_dump.cmo -mode S -o pa_r5rsr.ppo pa_r5rsr.ml

echo ocamlc.opt -warn-error A -I ../main -I ../boot -I ../lib -c -impl pa_r5rsr.ppo
ocamlc.opt -warn-error A -I ../main -I ../boot -I ../lib -c -impl pa_r5rsr.ppo

echo rm -f pa_r5rsr.ppo
rm -f pa_r5rsr.ppo
